// Generated by CoffeeScript 1.7.1

/*
A base class for objects that move around the game area. The can be updated and drawn.
 */
var Entity;

Entity = (function() {
  function Entity() {
    this.x = 0;
    this.y = 0;
    this.width = 0;
    this.height = 0;
    this.xVelocity = 0;
    this.yVelocity = 0;
  }


  /*
  Update the entity by the given number of steps.
   */

  Entity.prototype.update = function(steps) {
    this.x += this.xVelocity * steps;
    return this.y += this.yVelocity * steps;
  };


  /*
  Draw the entity on the given drawing surface.
   */

  Entity.prototype.draw = function(context) {
    context.fillStyle = '#fff';
    return context.fillRect(this.x, this.y, this.width, this.height);
  };


  /*
  Does this entity intersect with the given other entity?
   */

  Entity.prototype.intersect = function(other) {
    return this.y + this.height > other.y && this.y < other.y + other.height && this.x + this.width > other.x && this.x < other.x + other.width;
  };


  /*
  A helper method to transform degrees to radians
   */

  Entity.prototype.degreesToRadians = function(degrees) {
    return degrees * Math.PI / 180;
  };


  /*
  A helper method to transform radians to degrees.
   */

  Entity.prototype.radiansToDegrees = function(radians) {
    return radians * 180 / Math.PI;
  };

  return Entity;

})();
